# .streamlit/secrets.toml
[google]
gemini_api_key = "AIzaSyD8dYmlfLDp9xV2EUSWRf_zkiwqmusSLMg"

[youtube]
api_key = "AIzaSyDo5jkE6EHySmkx6wqDPV1w1KZ5JrEkG7s"

[database]
host = "localhost"
user = "root"
password = "mysql#7V"
database = "roadmap_db"
